<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>check_Day4</name>
   <tag></tag>
   <elementGuidId>43b02c51-d3e6-43d2-80a0-a17eabaad12e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='check']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#check</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d29db210-3f20-4bbc-8f68-7f59498470c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2834f26a-da1e-4daa-9e40-ebedbe1d5331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>85000|130|1</value>
      <webElementGuid>86fa9284-1f5d-4d4a-a00c-369f453165c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0ec0e933-f8b6-4ab8-bafc-ae92bf1b8f48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Day 4: Workshop</value>
      <webElementGuid>48d880ba-d278-4317-bc53-1a912171cdf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data</name>
      <type>Main</type>
      <value>500000</value>
      <webElementGuid>c5d814d2-eb59-4eb5-b16d-d1578dd923b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>check</value>
      <webElementGuid>f6902059-3e5e-4e5f-9ac3-ac62e246fc29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cartForm&quot;)/div[@class=&quot;col-md-8&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-1&quot;]/div[1]/input[@id=&quot;check&quot;]</value>
      <webElementGuid>7ce89a09-3027-4238-bc04-4abef2190836</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='check']</value>
      <webElementGuid>3df8bfbd-549b-4bb5-913b-ea8acd01fe14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='cartForm']/div/div/div/div/input</value>
      <webElementGuid>c22811d0-f59b-4d25-a830-bfd972945b17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>fecfd492-4190-4365-bc0e-3ee8879c8060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'Day 4: Workshop' and @id = 'check']</value>
      <webElementGuid>1fd1b754-1c8e-40e6-862d-cce6f186e875</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
