<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_eventLebih</name>
   <tag></tag>
   <elementGuidId>89230d7e-0801-4aa9-809a-b0f5e5a4be53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='eventLainnya']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#eventLainnya</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a5986914-f45b-4d62-a57d-a77022d769ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/event</value>
      <webElementGuid>1e96c1d5-4ecf-4bcf-86ac-fa552822be61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eventLainnya</value>
      <webElementGuid>bb470128-edbb-45ca-ba81-3a9227845a34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Lihat Event Lainnya</value>
      <webElementGuid>61194d37-ed0a-42f4-a8d0-1b2550508758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eventLainnya&quot;)</value>
      <webElementGuid>7bffcfe7-a627-444a-8b2d-90cf2c49b980</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='eventLainnya']</value>
      <webElementGuid>d5932322-e998-41c1-a7c3-baa6195fe4ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Modal_Success']/div/div[2]/a[2]</value>
      <webElementGuid>0fa98583-f37a-44e9-af16-9509dfda7814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Lihat Event Lainnya')]</value>
      <webElementGuid>7c93e32b-5cbf-4c8f-bfcd-68377964e6e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Day 3: Predict using Machine Learning'])[3]/following::a[2]</value>
      <webElementGuid>dce47f79-3eb7-41d4-a74a-cce8fd23f09e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2010-2021 Coding.ID All rights reserved.'])[1]/preceding::a[1]</value>
      <webElementGuid>5744b899-7c49-457d-862c-3585b0ddbf34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Course'])[4]/preceding::a[6]</value>
      <webElementGuid>e7239462-6a56-4895-b5da-9386045f84e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lihat Event Lainnya']/parent::*</value>
      <webElementGuid>9a4dd471-a2b7-405e-a7e2-e49fb1565523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/event')])[10]</value>
      <webElementGuid>20680eed-7714-4569-a22d-9f048e7e56d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/a[2]</value>
      <webElementGuid>20f9dcea-07fd-4bab-8e42-4335da0e45e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/event' and @id = 'eventLainnya' and (text() = ' Lihat Event Lainnya' or . = ' Lihat Event Lainnya')]</value>
      <webElementGuid>b6f8d0cb-6884-43f0-a55d-60e37b4f4752</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
